version: '3.8'

services:
  feishu-rag-chatbot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FEISHU_APP_ID=${FEISHU_APP_ID}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
      - FEISHU_VERIFICATION_TOKEN=${FEISHU_VERIFICATION_TOKEN}
      - FEISHU_ENCRYPT_KEY=${FEISHU_ENCRYPT_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped